<?php

declare(strict_types=1);

use Infrangible\CatalogProductOptionPrice\Block\Cart\Item\Options;
use Magento\Checkout\Helper\Data;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   2014-2025 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Escaper $escaper */
/** @var Options $block */

/** @var Data $checkoutHelper */
$checkoutHelper = $this->helper(Data::class);

$options = $block->getOptionList();
?>

<?php if ($options): ?>
    <?php $isFirst = true; ?>
    <table class="item-options">
        <?php foreach ($options as $option): ?>
            <?php $formatedOptionValue = $block->getFormatedOptionValue($option); ?>
            <tr class="item-option">
                <?php if ($isFirst): ?>
                    <td class="item-options-label" rowspan="<?= count($options); ?>"><?= __('Selected product options'); ?></td>
                <?php endif; ?>
                <td class="item-option-description">
                    <dt><?= $escaper->escapeHtml($option['label']) ?></dt>
                    <dd>
                        <?php if (isset($formatedOptionValue['full_view'])): ?>
                            <?= $escaper->escapeHtml($formatedOptionValue['full_view'], ['span', 'a']); ?>
                        <?php else: ?>
                            <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']); ?>
                        <?php endif; ?>
                    </dd>
                </td>
                <td class="item-option-price">
                    + <?= $escaper->escapeHtml($checkoutHelper->formatPrice($option['price']), ['span']); ?>
                </td>
            </tr>
            <?php $isFirst = false; ?>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<div class="actions-toolbar">
    <?= $block->getData('action_html'); ?>
</div>
